/*******************************************************************************
 * Raymond Shum
 * November 10, 2020
 * CST 338
 * Assignment 2
 * 
 * This program simulates a slot machine. The class "ThreeString" tracks the
 * "display" of the slot machine and the individual and total winnings. The
 * "Assig2" class is used to bet, "pull" the slot machine and calculate payout.
 * Within "Assig2", the main method holds the loop that allows the user to play
 * the game. Once the user exits the game, his score is displayed.
 ******************************************************************************/

import java.util.Scanner;
import java.lang.Math;

public class Assig2
{

   public static Scanner userInput = new Scanner(System.in);
   
   public static int getBet()
   {
      int bet = 0;

      //Prompts user for input until integer value between 0 and 100 is entered
      do 
      {
         System.out.printf("%nEnter your bet (0-100 or 0 to quit): ");
         bet = userInput.nextInt();
         if (bet < 0 || bet > 100)
            System.out.println("Invalid bet. Please try again.");
      } while(bet < 0 || bet > 100);

      return bet;
   }   

   public static ThreeString pull()
   {
      ThreeString pullString = new ThreeString();
      
      //Sets all 3 private member strings to string generated by randString()
      pullString.setString1(randString());
      pullString.setString2(randString());
      pullString.setString3(randString());

      return pullString;
   }

   private static String randString()
   {
      //Generate random integer between 0 and 999
      int randomNumber = (int)(Math.random() * 1000 - 1);

      //Returns string based on range corresponding to probabilities in spec
      if(randomNumber >= 1 && randomNumber <= 499)
         return "space";
      else if(randomNumber >= 500 && randomNumber <= 749)
         return "cherries";
      else if(randomNumber >= 750 && randomNumber <= 874)
         return "BAR";
      else
         return "7";
   }

   public static int getPayMultiplier(ThreeString thePull)
   {
      String firstEntry = thePull.getString1();
      String secondEntry = thePull.getString2();
      String thirdEntry = thePull.getString3();

      //Returns pay multiplier based on string sequence in spec sheet
      if (firstEntry == "cherries" && secondEntry != "cherries")
         return 5;
      else if (firstEntry == "cherries" && secondEntry == "cherries" &&
            thirdEntry != "cherries")
         return 15;
      else if (firstEntry == "cherries" && secondEntry == "cherries" &&
            thirdEntry == "cherries")
         return 30;
      else if (firstEntry == "BAR" && secondEntry == "BAR" && 
            thirdEntry == "BAR")
         return 50;
      else if (firstEntry == "7" && secondEntry == "7" && thirdEntry == "7")
         return 100;
      else
         return 0;
   }

   public static void display(ThreeString thePull, int winnings)
   {
      //Displays formatted text of 3 private member strings and winnings
      System.out.printf("Your pull is:%n%s%n", thePull.toString());
      
      //Displays winnings if amount > 0 and loss message if 0
      if (winnings == 0)
         System.out.println("Sorry, you lose.");
      else
         System.out.printf("Congratulations, you win: %d%n", winnings);
   }

   public static void main(String[] args)
   {
      //userBet is initialized with getBet() and displays first prompt that
      //user sees. Skips game loop if initial bet is 0
      int userBet = getBet();
      int payMultiplier, adjustedPay = 0;
      ThreeString slotDisplay = new ThreeString();

      //while loop runs continuously until user quits by entering 0
      //payMultipler is calculated using strings from slotDisplay
      //adjustedWinnings is calculated using payMultiplier and userBet
      //saveWinnings updates private members of slotDisplay
      while (userBet !=0)
      {
         slotDisplay = pull();
         payMultiplier = getPayMultiplier(slotDisplay);
         adjustedPay = userBet * payMultiplier;
         slotDisplay.saveWinnings(adjustedPay);
         display(slotDisplay, adjustedPay);
         userBet = getBet();
      }

      userInput.close();
      
      //Individual and total members are displayed once userBet = 0
      System.out.println(slotDisplay.toStringWinnings());
   }

}

class ThreeString
{
   public static final int MAX_LEN = 20;
   public static final int MAX_PULLS = 40;
   private static int[] pullWinnings = new int[MAX_PULLS];
   private static int numPulls = 0;
   private String string1, string2, string3;

   public ThreeString()
   {
      string1 = string2 = string3 = "";
   }

   //returns true if string is not null & length is less than MAX_LEN
   private boolean validString(String str)
   {
      if ((str != "") && (str.length() <= MAX_LEN))
         return true;
      else
         return false;
   }

   //mutator: updates string1 with replacementString if it passes validation
   public boolean setString1(String replacementString)
   {
      if (validString(replacementString))
      {
         string1 = replacementString;
         return true;
      }
      else
         return false;
   }

   public boolean setString2(String replacementString)
   {
      if (validString(replacementString))
      {
         string2 = replacementString;
         return true;
      }
      else
         return false;
   }

   public boolean setString3(String replacementString)
   {
      if (validString(replacementString))
      {
         string3 = replacementString;
         return true;
      }
      else
         return false;
   }

   //accessor: returns current value of string1
   public String getString1()
   {
      return string1;
   }

   public String getString2()
   {
      return string2;
   }

   public String getString3()
   {
      return string3;
   }

   //returns concatenated values of string1, string2 and string3
   public String toString()
   {
      return (string1 + " " + string2 + " " + string3);
   }

   //Assigns winnings to current position in pullWinnings array and iterates
   //numPulls. If MAX_PULLS has been reached, will no longer update
   public boolean saveWinnings(int winnings)
   {
      if (numPulls < MAX_PULLS)
      {
         pullWinnings[numPulls] = winnings;
         numPulls++;
         return true;
      }
      else
         return false;
   }

   //returns formatted results screen containing individual and total winnings
   public String toStringWinnings()
   {
      String winningsSummary = "\nYour individual winnings were:\n";
      int totalWinnings = 0;
      
      //Exhaustively pulls integer values from the pullWinnings array and
      //adds them to the string. White space is added after integers following
      //the first
      for (int i = 0; i < numPulls; i++)
      {
         if (i == 0)
            winningsSummary = winningsSummary + pullWinnings[i];
         else
            winningsSummary = winningsSummary + " " + pullWinnings[i];
         
         totalWinnings = totalWinnings + pullWinnings[i];
      }
      
      winningsSummary = winningsSummary + "\nYour total winnings were: "
            + "$" + totalWinnings;
      
      return winningsSummary;
   }
}

/* ------------------------------ OUTPUT -------------------------------------*/
/* --- RUN1 --- INPUT VALIDATION -----------------------------------------------

Enter your bet (0-100 or 0 to quit): -100
Invalid bet. Please try again.

Enter your bet (0-100 or 0 to quit): -1
Invalid bet. Please try again.

Enter your bet (0-100 or 0 to quit): 101
Invalid bet. Please try again.

Enter your bet (0-100 or 0 to quit): 1000
Invalid bet. Please try again.

Enter your bet (0-100 or 0 to quit): 0

Your individual winnings were:

Your total winnings were: $0
------------------------------------------------------------------------------*/
/* --- RUN2 --- INPUT VALIDATION -----------------------------------------------

Enter your bet (0-100 or 0 to quit): -1
Invalid bet. Please try again.

Enter your bet (0-100 or 0 to quit): 101
Invalid bet. Please try again.

Enter your bet (0-100 or 0 to quit): 1
Your pull is:
BAR cherries space
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 1
Your pull is:
cherries 7 cherries
Congratulations, you win: 5

Enter your bet (0-100 or 0 to quit): 1
Your pull is:
space space space
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 0

Your individual winnings were:
0 5 0
Your total winnings were: $5
------------------------------------------------------------------------------*/
/* --- RUN3 --- FULL RUN -------------------------------------------------------

Enter your bet (0-100 or 0 to quit): 1
Your pull is:
cherries space space
Congratulations, you win: 5

Enter your bet (0-100 or 0 to quit): 2
Your pull is:
space BAR space
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 3
Your pull is:
cherries space space
Congratulations, you win: 15

Enter your bet (0-100 or 0 to quit): 4
Your pull is:
BAR cherries space
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 5
Your pull is:
cherries BAR space
Congratulations, you win: 25

Enter your bet (0-100 or 0 to quit): 6
Your pull is:
space space space
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 7
Your pull is:
space space cherries
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 8
Your pull is:
cherries cherries space
Congratulations, you win: 120

Enter your bet (0-100 or 0 to quit): 9
Your pull is:
space 7 space
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 10
Your pull is:
7 7 space
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 11
Your pull is:
space space BAR
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 12
Your pull is:
BAR space cherries
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 13
Your pull is:
cherries space space
Congratulations, you win: 65

Enter your bet (0-100 or 0 to quit): 14
Your pull is:
space cherries space
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 15
Your pull is:
space space cherries
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 16
Your pull is:
space 7 space
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 17
Your pull is:
cherries BAR space
Congratulations, you win: 85

Enter your bet (0-100 or 0 to quit): 18
Your pull is:
cherries cherries space
Congratulations, you win: 270

Enter your bet (0-100 or 0 to quit): 19
Your pull is:
7 space 7
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 20
Your pull is:
cherries space 7
Congratulations, you win: 100

Enter your bet (0-100 or 0 to quit): 21
Your pull is:
space space space
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 22
Your pull is:
space cherries BAR
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 23
Your pull is:
cherries space space
Congratulations, you win: 115

Enter your bet (0-100 or 0 to quit): 24
Your pull is:
space cherries space
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 25
Your pull is:
cherries BAR space
Congratulations, you win: 125

Enter your bet (0-100 or 0 to quit): 26
Your pull is:
cherries space space
Congratulations, you win: 130

Enter your bet (0-100 or 0 to quit): 27
Your pull is:
space space BAR
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 28
Your pull is:
space space cherries
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 29
Your pull is:
BAR cherries cherries
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 30
Your pull is:
space BAR cherries
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 31
Your pull is:
cherries space space
Congratulations, you win: 155

Enter your bet (0-100 or 0 to quit): 32
Your pull is:
cherries space space
Congratulations, you win: 160

Enter your bet (0-100 or 0 to quit): 33
Your pull is:
space space BAR
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 34
Your pull is:
space BAR BAR
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 35
Your pull is:
7 cherries space
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 36
Your pull is:
cherries space cherries
Congratulations, you win: 180

Enter your bet (0-100 or 0 to quit): 37
Your pull is:
space space BAR
Sorry, you lose.

Enter your bet (0-100 or 0 to quit): 38
Your pull is:
cherries space space
Congratulations, you win: 190

Enter your bet (0-100 or 0 to quit): 39
Your pull is:
cherries space space
Congratulations, you win: 195

Enter your bet (0-100 or 0 to quit): 40
Your pull is:
cherries space cherries
Congratulations, you win: 200

Enter your bet (0-100 or 0 to quit): 0

Your individual winnings were:
5 0 15 0 25 0 0 120 0 0 0 0 65 0 0 0 85 270 0 100 0 0 115 0 125 130 0 0 0 0 155 160 0 0 0 180 0 190 195 200
Your total winnings were: $2135
------------------------------------------------------------------------------*/